object Dependency {
    object Version {
        const val coreKtx = "1.12.0"
        const val lifeCycleKtx = "2.6.2"
        const val compose = "1.8.1"
        const val composeBom = "2023.03.00"
        const val hilt = "2.47"
        const val retrofit = "2.9.0"
        const val gsonConverter = "2.10.1"
        const val material3 = "1.2.0-beta01"
        const val junit = "4.13.2"
        const val junitAndroidEx = "1.1.5"
        const val espresso = "3.5.0"
        const val testRunner = "1.5.0"
        const val testRules = "1.5.0"
        const val hiltGradlePluginVersion = "2.44"
        const val hiltJetpackVersion = "1.0.0-alpha03"
        const val hiltNavigationCompose = "1.0.0"
        const val dagger = "2.35.1"
        const val coil = "2.6.0"
        const val coilCompose = "2.5.0"
        const val composeNavigation = "2.5.3"
        const val retofitHttpLogInterceptor = "4.9.1"
        const val ktlint = "12.0.3"
        const val composeFoundation = "1.6.0-alpha06"
        const val jsonSerialization = "1.6.0"
        const val composeViewModel = "2.6.1"
    }

    const val coreKtx = "androidx.core:core-ktx:${Version.coreKtx}"
    const val lifeCycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Version.lifeCycleKtx}"
    const val compose = "androidx.activity:activity-compose:${Version.compose}"
    const val composeBom = "androidx.compose:compose-bom:${Version.composeBom}"
    const val composeNavigation = "androidx.navigation:navigation-compose:${Version.composeNavigation}"
    const val composeViewModel = "androidx.lifecycle:lifecycle-viewmodel-compose:${Version.composeViewModel}"
    const val composeUI = "androidx.compose.ui:ui"
    const val composeUIGraphics = "androidx.compose.ui:ui-graphics"
    const val composePreview = "androidx.compose.ui:ui-tooling"
    const val material3 = "androidx.compose.material3:material3-android:${Version.material3}"
    const val iconsCore = "androidx.compose.material:material-icons-core"
    const val iconsExtended = "androidx.compose.material:material-icons-extended"
    const val retrofit ="com.squareup.retrofit2:retrofit:${Version.retrofit}"
    const val retrofitGsonConverter = "com.squareup.retrofit2:converter-gson:${Version.retrofit}"
    const val retrofitHttpLogInterceptor = "com.squareup.okhttp3:logging-interceptor:${Version.retofitHttpLogInterceptor}"
    const val composeFoundation = "androidx.compose.foundation:foundation:${Version.composeFoundation}"
    const val jsonSerialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Version.jsonSerialization}"

    // Custom modules
    const val common = ":common"
    const val domain = ":domain"
    const val data = ":data"
    const val authentication = ":authentication"
    const val trending = ":trending"
    const val events = ":events"
    const val search = ":search"
    const val profile = ":profile"
    const val theme = ":theme"
    const val composeComponents = ":composeComponents"
    const val home = ":home"
    const val event = ":event"
    const val sharedApp = ":sharedApp"

    // Coil
    const val coil = "io.coil-kt:coil:${Version.coil}"
    const val coilCompose = "io.coil-kt:coil-compose:${Version.coilCompose}"

    // Dagger core
    const val dagger2 = "com.google.dagger:dagger:${Version.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Version.dagger}"

    // Hilt
    const val hilt = "com.google.dagger:hilt-android:${Version.hilt}"
    const val hiltDagger = "com.google.dagger:hilt-android-compiler:${Version.hilt}"
    const val hiltNav = "androidx.hilt:hilt-navigation-compose:${Version.hiltNavigationCompose}"

    // Testing
    const val junit = "junit:junit:${Version.junit}"
    const val junitAndroidEx = "androidx.test.ext:junit:${Version.junitAndroidEx}"
    const val espresso = "androidx.test.espresso:espresso-core:${Version.espresso}"
    const val composeJUnitUITest = "androidx.compose.ui:ui-test-junit4"
    const val composeUITooling = "androidx.compose.ui:ui-tooling"
    const val composeUITest = "androidx.compose.ui:ui-test-manifest"
    const val testRunner = "androidx.test:runner:${Version.testRunner}"
    const val testRules = "androidx.test:rules:${Version.testRules}"
}